// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxGjkZ4elFfVs9q8ytE8Z_nNQriA9GTZc',
    appId: '1:890573346022:web:9d88e491d8ba72a77dd727',
    messagingSenderId: '890573346022',
    projectId: 'broker-assist-bc405',
    authDomain: 'broker-assist-bc405.firebaseapp.com',
    storageBucket: 'broker-assist-bc405.firebasestorage.app',
    measurementId: 'G-RLZXEN17HR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADbr1pAOldS3Gl2RKGTg9R9kR4BkijV1c',
    appId: '1:890573346022:android:350f6b0a6650fd6d7dd727',
    messagingSenderId: '890573346022',
    projectId: 'broker-assist-bc405',
    storageBucket: 'broker-assist-bc405.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4lx00H19DlHElMtkmlLTOZAki62KLBtM',
    appId: '1:890573346022:ios:dcf45a3f0863a24e7dd727',
    messagingSenderId: '890573346022',
    projectId: 'broker-assist-bc405',
    storageBucket: 'broker-assist-bc405.firebasestorage.app',
    iosBundleId: 'com.example.brokerAssist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4lx00H19DlHElMtkmlLTOZAki62KLBtM',
    appId: '1:890573346022:ios:dcf45a3f0863a24e7dd727',
    messagingSenderId: '890573346022',
    projectId: 'broker-assist-bc405',
    storageBucket: 'broker-assist-bc405.firebasestorage.app',
    iosBundleId: 'com.example.brokerAssist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxGjkZ4elFfVs9q8ytE8Z_nNQriA9GTZc',
    appId: '1:890573346022:web:c299e29e5ab446587dd727',
    messagingSenderId: '890573346022',
    projectId: 'broker-assist-bc405',
    authDomain: 'broker-assist-bc405.firebaseapp.com',
    storageBucket: 'broker-assist-bc405.firebasestorage.app',
    measurementId: 'G-D060PL5KZ0',
  );
}
